import { existsSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { scan } from "../src/core/scanner.js";

function setup(prefix: string): string {
  const tmp = mkdtempSync(join(tmpdir(), prefix));
  writeFileSync(
    join(tmp, "package.json"),
    JSON.stringify({ name: "fixture", type: "module" }),
    "utf8",
  );
  return tmp;
}

function bigBody(name: string, salt: number): string {
  return `export function ${name}(input: number): number {
  const a = input * ${salt};
  const b = a + ${salt};
  const c = b * b;
  const d = c - input;
  const e = d / 2;
  const f = e + a;
  const g = f - 3;
  const h = g * input;
  const i = h + 7;
  const j = i / 4;
  const k = j * 11;
  const m = k - input;
  return m * m;
}
`;
}

describe("duplicates: sliding-window basics", () => {
  let tmp: string;
  beforeEach(() => {
    tmp = setup("slp-dup-window-");
  });
  afterEach(() => {
    if (existsSync(tmp)) rmSync(tmp, { recursive: true, force: true });
  });

  it("finds a cross-file duplicate of identical large bodies", async () => {
    writeFileSync(join(tmp, "a.ts"), `${bigBody("alpha", 1)}export const _a = alpha;\n`, "utf8");
    writeFileSync(join(tmp, "b.ts"), `${bigBody("beta", 1)}export const _b = beta;\n`, "utf8");

    const result = await scan({ rootDir: tmp, only: ["duplicates"] });
    const dups = result.issues.filter((i) => i.kind === "duplicate");
    expect(dups.length).toBeGreaterThan(0);
  });

  it("does NOT match files below the token threshold", async () => {
    writeFileSync(join(tmp, "a.ts"), "export const a = 1;\n", "utf8");
    writeFileSync(join(tmp, "b.ts"), "export const b = 1;\n", "utf8");

    const result = await scan({ rootDir: tmp, only: ["duplicates"] });
    expect(result.issues.filter((i) => i.kind === "duplicate")).toHaveLength(0);
  });

  it("skips generated files marked with @generated header", async () => {
    writeFileSync(
      join(tmp, "a.ts"),
      `// @generated by some-tool\n${bigBody("alpha", 1)}export const _a = alpha;\n`,
      "utf8",
    );
    writeFileSync(
      join(tmp, "b.ts"),
      `// @generated by some-tool\n${bigBody("beta", 1)}export const _b = beta;\n`,
      "utf8",
    );

    const result = await scan({ rootDir: tmp, only: ["duplicates"] });
    expect(result.issues.filter((i) => i.kind === "duplicate")).toHaveLength(0);
  });

  it("skips files marked DO NOT EDIT", async () => {
    writeFileSync(
      join(tmp, "a.ts"),
      `// DO NOT EDIT — auto-generated\n${bigBody("alpha", 1)}export const _a = alpha;\n`,
      "utf8",
    );
    writeFileSync(
      join(tmp, "b.ts"),
      `// DO NOT EDIT — auto-generated\n${bigBody("beta", 1)}export const _b = beta;\n`,
      "utf8",
    );

    const result = await scan({ rootDir: tmp, only: ["duplicates"] });
    expect(result.issues.filter((i) => i.kind === "duplicate")).toHaveLength(0);
  });

  it("scores cross-file matches higher than same-file ones", async () => {
    writeFileSync(
      join(tmp, "a.ts"),
      `${bigBody("alpha", 1)}${bigBody("alphaCousin", 1)}export const _a = [alpha, alphaCousin];\n`,
      "utf8",
    );
    writeFileSync(
      join(tmp, "b.ts"),
      `${bigBody("beta", 1)}export const _b = beta;\n`,
      "utf8",
    );

    const result = await scan({ rootDir: tmp, only: ["duplicates"] });
    const dups = result.issues.filter((i) => i.kind === "duplicate");
    const crossFile = dups.find(
      (d) => d.kind === "duplicate" && d.matches.some((m) => m.file !== d.primary.file),
    );
    const sameFile = dups.find(
      (d) => d.kind === "duplicate" && d.matches.every((m) => m.file === d.primary.file),
    );
    if (crossFile && sameFile) {
      expect(crossFile.confidence).toBeGreaterThan(sameFile.confidence);
    } else {
      expect(crossFile).toBeDefined();
    }
  });

  it("reports a sensible preview snippet (first ~10 tokens)", async () => {
    writeFileSync(join(tmp, "a.ts"), `${bigBody("alpha", 1)}export const _a = alpha;\n`, "utf8");
    writeFileSync(join(tmp, "b.ts"), `${bigBody("beta", 1)}export const _b = beta;\n`, "utf8");

    const result = await scan({ rootDir: tmp, only: ["duplicates"] });
    const dup = result.issues.find((i) => i.kind === "duplicate");
    expect(dup).toBeDefined();
    if (dup?.kind === "duplicate") {
      expect(dup.preview.length).toBeGreaterThan(0);
      expect(dup.preview.length).toBeLessThanOrEqual(80);
    }
  });
});

describe("duplicates: handles template literals safely", () => {
  let tmp: string;
  beforeEach(() => {
    tmp = setup("slp-dup-template-");
  });
  afterEach(() => {
    if (existsSync(tmp)) rmSync(tmp, { recursive: true, force: true });
  });

  it("does not crash when bodies contain ${...} template substitutions", async () => {
    const body = (name: string) => `export function ${name}(d: { y: number; m: number; day: number }): string {
  const y = d.y;
  const m = String(d.m).padStart(2, "0");
  const day = String(d.day).padStart(2, "0");
  const a = \`\${y}-\${m}-\${day}\`;
  const b = \`\${y}/\${m}/\${day}\`;
  const c = \`\${day}.\${m}.\${y}\`;
  return a + b + c;
}
`;
    writeFileSync(join(tmp, "a.ts"), `${body("formatA")}export const _a = formatA;\n`, "utf8");
    writeFileSync(join(tmp, "b.ts"), `${body("formatB")}export const _b = formatB;\n`, "utf8");

    const result = await scan({ rootDir: tmp, only: ["duplicates"] });
    expect(result.filesScanned).toBeGreaterThan(0);
  });
});
