import { existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { scan } from "../src/core/scanner.js";

function setup(prefix: string): string {
  const tmp = mkdtempSync(join(tmpdir(), prefix));
  writeFileSync(
    join(tmp, "package.json"),
    JSON.stringify({ name: "fixture", type: "module", main: "./entry.ts" }),
    "utf8",
  );
  writeFileSync(join(tmp, "entry.ts"), `export const APP = 1;\n`, "utf8");
  return tmp;
}

function write(root: string, rel: string, content: string): void {
  const target = join(root, rel);
  mkdirSync(target.replace(/[\\/][^\\/]+$/, ""), { recursive: true });
  writeFileSync(target, content, "utf8");
}

describe("generated files are skipped by all detectors", () => {
  let tmp: string;
  beforeEach(() => {
    tmp = setup("slp-generated-");
  });
  afterEach(() => {
    if (existsSync(tmp)) rmSync(tmp, { recursive: true, force: true });
  });

  it("`foo.generated.ts` filename pattern is skipped", async () => {
    write(tmp, "schema.generated.ts", `export const UnusedFromGen = 1;\nexport function alsoUnused() { return 2; }\n`);
    const result = await scan({ rootDir: tmp, verbose: true });
    const flagged = result.issues
      .filter((i) => (i.kind === "dead-code" || i.kind === "unused-export") && "symbol" in i)
      .map((i) => ("symbol" in i ? i.symbol : ""));
    expect(flagged).not.toContain("UnusedFromGen");
    expect(flagged).not.toContain("alsoUnused");
  });

  it("`foo.gen.ts` filename pattern is skipped", async () => {
    write(tmp, "types.gen.ts", `export interface Generated { id: string }\nexport const HELPER = "x";\n`);
    const result = await scan({ rootDir: tmp, verbose: true });
    const flagged = result.issues
      .filter((i) => (i.kind === "dead-code" || i.kind === "unused-export") && "symbol" in i)
      .map((i) => ("symbol" in i ? i.symbol : ""));
    expect(flagged).not.toContain("Generated");
    expect(flagged).not.toContain("HELPER");
  });

  it("`foo.pb.ts` and `foo_pb.ts` (protobuf) are skipped", async () => {
    write(tmp, "user.pb.ts", `export interface UserMessage { name: string }\nexport function encodeUser(u: UserMessage): Uint8Array { return new TextEncoder().encode(u.name); }\n`);
    write(tmp, "order_pb.ts", `export interface OrderMessage { id: number }\nexport const ORDER_KIND = "order";\n`);
    const result = await scan({ rootDir: tmp, verbose: true });
    const flagged = result.issues
      .filter((i) => (i.kind === "dead-code" || i.kind === "unused-export") && "symbol" in i)
      .map((i) => ("symbol" in i ? i.symbol : ""));
    expect(flagged).not.toContain("UserMessage");
    expect(flagged).not.toContain("encodeUser");
    expect(flagged).not.toContain("OrderMessage");
    expect(flagged).not.toContain("ORDER_KIND");
  });

  it("file with `@generated` marker in header is skipped even without naming convention", async () => {
    write(
      tmp,
      "src/api.ts",
      `// @generated by openapi-generator-cli\n// do not edit by hand\n\nexport interface ApiResponse { ok: boolean }\nexport function unusedHelper() { return 1; }\n`,
    );
    const result = await scan({ rootDir: tmp, verbose: true });
    const flagged = result.issues
      .filter((i) => (i.kind === "dead-code" || i.kind === "unused-export") && "symbol" in i)
      .map((i) => ("symbol" in i ? i.symbol : ""));
    expect(flagged).not.toContain("ApiResponse");
    expect(flagged).not.toContain("unusedHelper");
  });

  it("generated files DO count as consumers — symbols they import stay alive", async () => {
    write(tmp, "lib/util.ts", `export function realUtil() { return 1; }\n`);
    write(
      tmp,
      "schema.generated.ts",
      `import { realUtil } from "./lib/util.js";\nexport const VALUE = realUtil();\n`,
    );
    const result = await scan({ rootDir: tmp, verbose: true });
    const flagged = result.issues
      .filter((i) => (i.kind === "dead-code" || i.kind === "unused-export") && "symbol" in i)
      .map((i) => ("symbol" in i ? i.symbol : ""));
    expect(flagged).not.toContain("realUtil");
  });

  it("non-generated files alongside generated files still flag real dead-code", async () => {
    write(tmp, "schema.generated.ts", `export const Generated = 1;\n`);
    write(tmp, "src/orphan.ts", `export function realDead() { return 1; }\n`);
    const result = await scan({ rootDir: tmp, verbose: true });
    const flagged = result.issues
      .filter((i) => (i.kind === "dead-code" || i.kind === "unused-export") && "symbol" in i)
      .map((i) => ("symbol" in i ? i.symbol : ""));
    expect(flagged).toContain("realDead");
  });

  it("smell detectors do not fire inside generated files", async () => {
    write(
      tmp,
      "schema.generated.ts",
      `export function wrap(x: number) { return inner(x); }\nfunction inner(x: number) { return x; }\nexport async function noAwait() { return 1; }\nexport function badCatch() { try { JSON.parse("x"); } catch {} return 0; }\n`,
    );
    const result = await scan({ rootDir: tmp, verbose: true });
    const smells = result.issues.filter(
      (i) =>
        i.kind === "empty-wrapper" ||
        i.kind === "useless-async" ||
        i.kind === "empty-catch",
    );
    expect(smells).toHaveLength(0);
  });
});
