export const SUPPORTED_EXTENSIONS = ["ts", "tsx", "js", "jsx", "mjs", "cjs"] as const;

export const DEFAULT_IGNORE_PATTERNS: readonly string[] = [
  "**/node_modules/**",
  "**/.git/**",
  "**/dist/**",
  "**/build/**",
  "**/.next/**",
  "**/.nuxt/**",
  "**/.turbo/**",
  "**/.cache/**",
  "**/coverage/**",
  "**/out/**",
  "**/*.min.js",
  "**/*.d.ts",
];

export const TEST_FILE_PATTERNS: readonly string[] = [
  "**/*.test.{ts,tsx,js,jsx,mjs,cjs}",
  "**/*.spec.{ts,tsx,js,jsx,mjs,cjs}",
  "**/*.e2e.{ts,tsx,js,jsx,mjs,cjs}",
  "**/__tests__/**",
  "**/__mocks__/**",
  "**/tests/**",
  "**/test/**",
  "**/e2e/**",
];

const TEST_FILENAME_REGEX =
  /\.(test|spec|e2e|bench|demo|example|story|stories|fixture|fixtures|mock|mocks)\.[mc]?[jt]sx?$|(^|\/)((vitest|jest|playwright)[.-]?setup|setupTests|setup-tests|vitestSetup|jestSetup)\.[mc]?[jt]sx?$/;

const TEST_DIR_REGEX =
  /(^|\/)(__[a-z0-9_-]+__|tests?|e2e|benches?|benchmarks?|perf-measures|playground|generated|gen)(\/|$)/i;

const GENERATED_FILENAME_REGEX =
  /\.(gen|generated|pb)\.[mc]?[jt]sx?$|_pb\.[mc]?[jt]sx?$/;

const GENERATED_CONTENT_MARKERS = [
  "@generated",
  "auto-generated",
  "AUTOGENERATED",
  "DO NOT EDIT",
];

export function isTestFilePath(absoluteFilePath: string, projectRoot: string): boolean {
  const normFile = absoluteFilePath.replace(/\\/g, "/");
  if (TEST_FILENAME_REGEX.test(normFile)) return true;
  const normRoot = projectRoot.replace(/\\/g, "/");
  if (!normFile.startsWith(normRoot)) return TEST_DIR_REGEX.test(normFile);
  return TEST_DIR_REGEX.test(normFile.slice(normRoot.length).replace(/^\//, ""));
}

export function isGeneratedFilePath(absoluteFilePath: string): boolean {
  return GENERATED_FILENAME_REGEX.test(absoluteFilePath.replace(/\\/g, "/"));
}

export function isGeneratedSource(source: string): boolean {
  const head = source.slice(0, 500);
  return GENERATED_CONTENT_MARKERS.some((m) => head.includes(m));
}

export const DUPLICATE_MIN_TOKENS = 50;
export const DUPLICATE_MAX_FILE_LINES = 5000;

export interface ScanOptions {
  rootDir: string;
  paths?: string[];
  only?: ReadonlyArray<
    "duplicates" | "dead-code" | "empty-wrappers" | "ai-signatures" | "code-smells"
  >;
  ignore?: string[];
  color?: boolean;
  minConfidence?: number;
  verbose?: boolean;
  externallyConsumed?: ReadonlySet<string>;
  // set by scanMonorepo: suppresses orphan-file insights in per-package sub-scans.
  inMonorepoSubScan?: boolean;
}

export const FIX_MIN_CONFIDENCE = 0.8;
